directives:
  # Add iiwa_thanos
    - add_model:
        name: iiwa_thanos
        file: package://bimanual/urdf/med_gamma.urdf
        default_joint_positions:
            iiwa_joint_1: [0]
            iiwa_joint_2: [0.0]
            iiwa_joint_3: [0]
            iiwa_joint_4: [0]
            iiwa_joint_5: [0]
            iiwa_joint_6: [0]
            iiwa_joint_7: [0]
    - add_weld:
        parent: world
        child: iiwa_thanos::base
  # Add iiwa_medusa
    - add_model:
        name: iiwa_medusa
        file: package://bimanual/urdf/med.urdf
        default_joint_positions:
            iiwa_joint_1: [0]
            iiwa_joint_2: [0.0]
            iiwa_joint_3: [0]
            iiwa_joint_4: [0]
            iiwa_joint_5: [0]
            iiwa_joint_6: [0]
            iiwa_joint_7: [0]
    - add_frame:
        name: iiwa_medusa_origin
        X_PF:
            base_frame: world
            rotation: !Rpy { deg: [0.0, 0.0, 0.0]}
            translation: [0, 1.2192, 0.0]
    - add_weld:
        parent: iiwa_medusa_origin
        child: iiwa_medusa::base
        
    - add_frame:
        name: thanos_finger
        X_PF:
            base_frame: iiwa_thanos::iiwa_link_ee_kuka
            rotation: !Rpy { deg: [0.0, 0.0, 0.0]}
            translation: [0.0, 0.0, 0.13]

    - add_frame:
        name: medusa_finger
        X_PF:
            base_frame: iiwa_medusa::iiwa_link_ee_kuka
            rotation: !Rpy {deg: [0.0, 0.0, 0.0]}
            translation: [0.0, 0.0, 0.13]