# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
          { id: 4, size: 0.02, name: ft_tag },
          { id: 5, size: 0.02, name: tag_5 },
          { id: 6, size: 0.02, name: tag_6 },
          { id: 7, size: 0.02, name: tag_7 }
  ]
tag_bundles:
  [
    {
      name: 'tag_bundle_calibration',
      layout:
        [
          { id: 100, size: 0.03, x: 0., y: -0.054, z: 0., qx: 0, qy: 0, qz: 0, qw: 1},
          { id: 101, size: 0.03, x: 0.054, y: 0., z: 0., qx: 0, qy: 0, qz: 0.70710678, qw: 0.70710678},
          { id: 102, size: 0.03, x: 0., y: 0.054, z: 0., qx: 0, qy: 0, qz: 1, qw: 0},
          { id: 103, size: 0.03, x: -0.054, y: -0., z: 0., qx: 0, qy: 0, qz: 0.70710678, qw: -0.70710678},
        ]

    },
  ]